# Generated by Django 5.0.6 on 2024-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addconsignment',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='addconsignmenttemp',
            name='balance',
        ),
        migrations.AddField(
            model_name='tripsheetprem',
            name='weightAmt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tripsheettemp',
            name='weightAmt',
            field=models.IntegerField(null=True),
        ),
    ]
