# Generated by Django 5.0.6 on 2024-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_alter_account_track_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='AdvGiven',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='DriverName',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='LTRate',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='Ltr',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='VehicalNo',
        ),
        migrations.RemoveField(
            model_name='tripsheettemp',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='disel',
            name='trip_id',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripsheettemp',
            name='weightAmt',
            field=models.FloatField(null=True),
        ),
    ]
