# Generated by Django 5.0.6 on 2024-09-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0004_remove_tripsheettemp_advgiven_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='commission',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='commission',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.AddField(
            model_name='branch',
            name='agency',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='aadhar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='door_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='hamali',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='st_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignment',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='door_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='hamali',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='st_charge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='weightAmt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
