# Generated by Django 5.0.6 on 2024-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0005_rename_commission_addconsignment_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
                ('services', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emission',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emissiondate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='incurence',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='incurencedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permitdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rccard',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rccardate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='taxdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhar',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
