# Generated by Django 5.0.6 on 2024-10-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0008_remove_branch_agency_remove_branch_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
